### PR TITLE
allow user to control the use of PV put completion

### PR DESCRIPTION
**Pull request by hinxx**
Possible solution for #2.

### CODE REVIEW

**Comment by darcato** [comment]
Why not having an optional argument on the put method, for example ``wait_complete=True``?

**Comment by hinxx** [comment]
You're right, having an optional argument on the put itself seems more straightforward. I'll rework the PR and try to add doc change, too.

I was also thinking about the `putComplete()` matter. If the interpretation of it is strictly meant as an indication of async completion, then it would make sense that `fsmIO._putComplete` remains False in cases when `wait_complete=False` is used and the trigger with 'putcomp' is never issued in such case. If the PV put would fail the `epicsIO.put()` reports an error already.

What do you think?

**Comment by darcato** [comment]
I know that I proposed the name ``wait_complete`` but given the additional context probably it's better to stick with ``use_complete`` (the same as the underlying code) or ``use_callbacks``, since this flag only enables/disables the put callbacks but it never waits for something.

**Comment by hinxx** [comment]
Re-based to current master code, too.

**Pull request merged**
